### ISSUE TITLE
Unable to install spsenv

### ISSUE THREAD

**Issue by grpatryan** [gwm17/spspy#4]
I'm unable to execute the line to install the spsenv from environment.yml. I get an error saying that the solving environment failed. I'm running  Windows 11 Home Version 22H2 (OS Build 22624.1755) and python 3.9.16.

**Comment by grpatryan** [comment]
![conda_error](https://github.com/gwm17/spspy/assets/108153444/beff7852-258a-4d0d-8fbd-956348d05e62)
![conda_update](https://github.com/gwm17/spspy/assets/108153444/e0d20610-5020-4460-a922-c04fb2f93dd9)

**Comment by gwm17** [comment]
So looking at this it definitely looks like a conda problem... I'm not sure why conda is refusing to update, but I'm certain that that is what is causing it to miss any packages that need installed, because it probably can't access the most recent repositories. Is it possible to try a fresh install of Anaconda or try using pip as an alternative?

**Comment by gwm17** [comment]
I'm marking this as closed due to inactivity, but feel free to reopen if the issue is unfixed
